In [1]:
import numpy as np

In [3]:
arr = np.array ([1,2,3,4,5])

In [4]:
print(arr)

[1 2 3 4 5]


In [5]:
print(type(arr))

<class 'numpy.ndarray'>


In [6]:
arr

array([1, 2, 3, 4, 5])

In [7]:
arr.ndim

1

In [8]:
arr.shape

(5,)

In [9]:
!pip install numpy

In [10]:
np.__version__

'1.20.1'

In [11]:
import pandas as pd

In [12]:
pd.__version__

'1.2.4'

In [16]:
import numpy

In [17]:
arr = numpy.array([1,2,3,4,5,6])

In [18]:
print(arr)

[1 2 3 4 5 6]


In [20]:
arr.dtype

dtype('int32')

In [21]:
import numpy as np

In [22]:
arr = np.array((1,2,3,4,5))

In [23]:
print(arr)

[1 2 3 4 5]


In [24]:
arr.dtype

dtype('int32')

In [25]:
arr.ndim

1

In [26]:
arr = np.array(42)

In [27]:
print(arr)

42


In [28]:
arr.ndim

0

In [29]:
arr.dtype

dtype('int32')

In [30]:
arr.size

1

In [32]:
arr = np.array([1,2,4,5,6,9])

In [33]:
print(arr)

[1 2 4 5 6 9]


In [34]:
arr.size

6

In [35]:
arr.dtype

dtype('int32')

In [36]:
arr.ndim

1

In [42]:
arr = np.array([[1,2,4,5,6],[23,4,54,6,45],[21,43,234,23,45]])

In [43]:
print(arr)

[[  1   2   4   5   6]
 [ 23   4  54   6  45]
 [ 21  43 234  23  45]]


In [44]:
arr.size

15

In [45]:
arr.ndim

2

In [46]:
arr.shape

(3, 5)

In [48]:
arr = np.array([[[23,23,43,45,1],[54,23,65,7,4],[22,12,5,67,64],[54,67,34,12,5],[43,78,5,23,2]]])

In [49]:
print(arr)

[[[23 23 43 45  1]
  [54 23 65  7  4]
  [22 12  5 67 64]
  [54 67 34 12  5]
  [43 78  5 23  2]]]


In [50]:
arr.ndim

3

In [51]:
arr.dtype

dtype('int32')

In [52]:
arr.shape

(1, 5, 5)

In [53]:
arr.size

25

In [54]:
print(arr.ndim)

3


In [55]:
arr = np.array([1,2,34,5,6,76,87,98], ndmin=4)

In [56]:
print(arr)

[[[[ 1  2 34  5  6 76 87 98]]]]


In [57]:
arr.ndim

4

In [58]:
arr = np.array([1,3,4,5,6])

In [59]:
print(arr)

[1 3 4 5 6]


In [60]:
arr[0]

1

In [61]:
arr[1]

3

In [72]:
arr = np.array([1,2,3,4,5])

In [73]:
arr[0] + arr[1]

3

In [74]:
aray = arr[1] + arr[2]

In [69]:
arr

5

In [75]:
arr

array([1, 2, 3, 4, 5])

In [76]:
aray

5

In [77]:
arr = np.array([[1,2,3,4,5],[5,4,3,2,1]])

In [78]:
arr[0, 2]

3

In [79]:
arr[1, 4]

1

In [80]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

In [82]:
arr[1, -1]

10

In [86]:
arr = np.array([1,2,3,4,5,6])

In [97]:
slice1 = arr[1:5]

In [98]:
slice1

array([2, 3, 4, 5])

In [96]:
arr

array([1, 2, 3, 4, 5, 6])

In [90]:
arr.size

6

In [91]:
arr.shape


(6,)

In [92]:
arr.dtype

dtype('int32')

In [93]:
arr.ndim

1

In [94]:
array

5

In [99]:
arr = np.array([1,2,3,4,5,6])

In [100]:
slice2 = arr[3:]

In [101]:
arr

array([1, 2, 3, 4, 5, 6])

In [102]:
slice2

array([4, 5, 6])

In [103]:
arr = np.array([1,2,3,4,5,6,7])

In [104]:
slice3 = arr[:4]

In [105]:
slice3

array([1, 2, 3, 4])

In [112]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

In [113]:
#dash = arr[-3:-1]

In [114]:
#dash

In [118]:
abc = arr[-2:-2]

In [119]:
abc

array([], dtype=int32)

In [120]:
print(abc)

[]


In [121]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

In [128]:
ab = arr[-4:-2]

In [129]:
ab

array([4, 5])

# Question?

In [145]:
arr = np.array([1, 2, 3, 4, 5, 6, 7,8])

In [148]:
dash = arr[1::3]

In [149]:
dash

array([2, 5, 8])

In [141]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

In [142]:
print(arr[::2])

[1 3 5 7]


In [150]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

In [151]:
slic = arr[1, 1:4]

In [152]:
slic

array([7, 8, 9])

In [153]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

In [154]:
slic = arr[0:2, 2]

In [155]:
slic

array([3, 8])

In [156]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

In [157]:
dash = arr[0:2, 1:4]

In [158]:
dash

array([[2, 3, 4],
       [7, 8, 9]])

In [159]:
arr = np.array([1, 2, 3, 4])

In [160]:
arr.dtype

dtype('int32')

In [161]:
arr = np.array(['apple', 'banana', 'cherry'])

In [162]:
arr.dtype

dtype('<U6')

In [163]:
print(arr.dtype)

<U6


In [164]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

In [165]:
arr.shape

(2, 4)

In [166]:
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [167]:
arr = np.array([1, 2, 3, 4], ndmin=5)

In [168]:
arr

array([[[[[1, 2, 3, 4]]]]])

In [169]:
arr.shape

(1, 1, 1, 1, 4)